export DOCKER_REGISTRY_HOST=${DOCKER_REGISTRY_HOST}
export DOCKER_REGISTRY_PORT=${DOCKER_REGISTRY_PORT}
export DOCKER_VERSION=latest
export REPOSITORY_HOST=repository.chnoumis.org
export REPOSITORY_PROXY_AUTH=${REPOSITORY_PROXY_AUTH}
export REPOSITORY_PRIVATE_AUTH=${REPOSITORY_PRIVATE_AUTH}